/*============================================================================
 * @file vsen_common.h
 *
 * Vsen Common defination
 *
 * Copyright (c) 2020 vivo Technologies. All Rights Reserved.
 */
#ifndef _VSEN_COMMON_
#define _VSEN_COMMON_

/*
* NOTICE:Please keep this command as:
*  A BB
*  A -->  sensor ID, like porximity sensor as 8.refer to Sensor.java
*  BB --> cmds,as you like.
* ALSO NOTICE -- Keep this head file as same as kernel's
*
*/
typedef enum VSEN_ENG_CMD {
/* Accelerometer Sensor */
SENSOR_COMMAND_ACCEL_SELF_TEST              = 0x100,
SENSOR_COMMAND_ACCEL_READ_REG               = 0x101,
SENSOR_COMMAND_ACCEL_WRITE_REG              = 0x102,
SENSOR_COMMAND_ACCEL_SET_ENG_CALI_DATA      = 0x103,
SENSOR_COMMAND_ACCEL_CLR_INT                = 0x104,
SENSOR_COMMAND_ACCEL_READ_INT               = 0x105,

/* Magnetic Sensor */
SENSOR_COMMAND_MAG_SELF_TEST                = 0x200,
SENSOR_COMMAND_MAG_READ_REG                 = 0x201,
SENSOR_COMMAND_MAG_WRITE_REG                = 0x202,

/* Gyroscope Sensor */
SENSOR_COMMAND_GYRO_SELF_TEST               = 0x400,
SENSOR_COMMAND_GYRO_SET_ENG_CALI_DATA       = 0x401,
SENSOR_COMMAND_GYRO_GET_RAW_DATA            = 0x402,
SENSOR_COMMAND_GYRO_CLR_INT                 = 0x403,
SENSOR_COMMAND_GYRO_READ_INT                = 0x404,


/* Light Sensor */
SENSOR_COMMAND_LIGHT_GET_PARA_INDEX         = 0x500,
SENSOR_COMMAND_LIGHT_BOOST_NOTIRY           = 0x501,
SENSOR_COMMAND_LIGHT_RAW_DATA               = 0x502,
SENSOR_COMMAND_LIGHT_READ_REG_DATA          = 0x503,
SENSOR_COMMAND_LIGHT_WRITE_REG_DATA         = 0x504,
SENSOR_COMMAND_LIGHT_SET_NOTIFY_BRIGHTNESS  = 0x505,
SENSOR_COMMAND_LIGHT_SET_SAMPLE_PARAM_MODE  = 0x506,
SENSOR_COMMAND_LIGHT_GET_SAMPLE_PARAM_DATA  = 0x507,

/* Proximity Sensor */
SENSOR_COMMAND_PROX_CHECK_INT               = 0x800,
SENSOR_COMMAND_PROX_READ_INT                = 0x801,
SENSOR_COMMAND_PROX_GET_DATA_RANGE          = 0x802,
SENSOR_COMMAND_PROX_GET_STATUS              = 0x803,
SENSOR_COMMAND_PROX_READ_REG_DATA           = 0x804,
SENSOR_COMMAND_PROX_WRITE_REG_DATA          = 0x805,
SENSOR_COMMAND_PROX_SET_CALI_DATA           = 0x806,
SENSOR_COMMAND_PROX_SET_ENG_CALI_DATA       = 0x807,
SENSOR_COMMAND_PROX_NOTIFY_THRES_LEVEL      = 0x808,
SENSOR_COMMAND_PROX_GET_PARA_INDEX          = 0x809,
SENSOR_COMMAND_PROX_CHIP_RESET              = 0x80A,
SENSOR_COMMAND_PROX_SET_PRE_CALIBRATION     = 0x80B,
SENSOR_COMMAND_PROX_GET_PRE_CALIBRATION     = 0x80C,
SENSOR_COMMAND_PROX_SET_CALI_OFFSET_DATA    = 0x80D,
SENSOR_COMMAND_PROX_SET_PRE_CALI            = 0x80E,
SENSOR_COMMAND_PROX_SET_DEFAUT_CHANEL       = 0x80F,
SENSOR_COMMAND_PROX_SET_ENG_MODE            = 0x810,
SENSOR_COMMAND_PROX_NOTIFY_TEMP_CALI        = 0x811,
SENSOR_COMMAND_PROX_NOTIFY_PS_BROKEN        = 0x812,
SENSOR_COMMAND_PROXIMITY_POWER_LEVEL        = 0x813,
SENSOR_COMMAND_PROXIMITY_GET_CALIOFFSET     = 0x814,
SENSOR_COMMAND_PROX_GET_RECALI_RESULT       = 0x815,

/* Sar Sensor-type:66559*/
SENSOR_COMMAND_SAR_ENABLE_CALI              = 0x590,
SENSOR_COMMAND_SAR_GET_CALI                 = 0x591,
SENSOR_COMMAND_SAR_READ_REG                 = 0x592,
SENSOR_COMMAND_SAR_WRITE_REG                = 0x593,
SENSOR_COMMAND_SAR_GET_NEAR_FAR             = 0x594,
SENSOR_COMMAND_SAR_FORCE_TO_NEAR            = 0x595,
SENSOR_COMMAND_SAR_FORCE_TO_NOSAR           = 0x596,
SENSOR_COMMAND_SAR_GET_DIFF_OFFSET          = 0x597,

SENSOR_COMMAND_SAR_B_ENABLE_CALI              = 0x690,
SENSOR_COMMAND_SAR_B_GET_CALI                 = 0x691,
SENSOR_COMMAND_SAR_B_READ_REG                 = 0x692,
SENSOR_COMMAND_SAR_B_WRITE_REG                = 0x693,
SENSOR_COMMAND_SAR_B_GET_NEAR_FAR             = 0x694,
SENSOR_COMMAND_SAR_B_FORCE_TO_NEAR            = 0x695,
SENSOR_COMMAND_SAR_B_FORCE_TO_NOSAR           = 0x696,
SENSOR_COMMAND_SAR_B_GET_DIFF_OFFSET          = 0x697,

} vsen_eng_cmd;
#define VSEN_COMMAND_ARGS_SIZE 10

#define VSEN_ALS_BOOST_REPORT_COUNT 20

#define VSEN_REPORT_BOOST_INTERVAL 20
#define VSEN_REPORT_NORMAL_INTERVAL 200
#define VSEN_REPORT_ERROR_RETRY_INTERVAL 20

#define VSEN_REPORT_ERROR_RETRY_COUNT 20

#endif
