#drivers/input/touchscreen/focaltech_ts/focaltech_test
#
# Makefile for test module
#
# Linux driver folder
obj-y += focaltech_test_config_ft8006.o	
obj-y += focaltech_test_ft8006.o
obj-y += focaltech_test_ft8736.o
obj-y += focaltech_test_config_ft8736.o
obj-y += focaltech_test_supported_ic.o

