#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-$(CONFIG_MTK_LENS)   += main/
obj-$(CONFIG_MTK_LENS)   += main2/
#obj-$(CONFIG_MTK_LENS)   += main3/
obj-$(CONFIG_MTK_LENS)   += sub/
#obj-$(CONFIG_MTK_LENS)   += sub2/
ifdef CONFIG_MTK_CAM_PD2083F_EX
obj-$(CONFIG_MTK_LENS)   += ois/
endif