#
# Makefile for the Synaptics TCM touchscreen driver.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_TCM_SPI) += synaptics_tcm_spi.o
obj-y += synaptics_tcm_i2c.o
obj-y += synaptics_tcm_core.o
obj-y += synaptics_tcm_touch.o
obj-y += synaptics_tcm_device.o
obj-y += synaptics_tcm_testing.o
obj-y += synaptics_tcm_reflash.o
obj-y += synaptics_tcm_recovery.o
obj-y += synaptics_tcm_diagnostics.o
obj-y += synaptics_tcm_vivo_interface.o
