
VAUDIT_FEAT(SYSCALL, true)/*0x1*/
VAUDIT_FEAT(SYSFSPROC, true)
VAUDIT_FEAT(BINDER, true)
VAUDIT_FEAT(IO, true)
VAUDIT_FEAT(CPU, true)
VAUDIT_FEAT(MEMORY, true)
VAUDIT_FEAT(NET, true)
VAUDIT_FEAT(FS, true)
VAUDIT_FEAT(TOUCHPANEL, true)
VAUDIT_FEAT(INTERRUPT, true)
VAUDIT_FEAT(DRIVER, true)
VAUDIT_FEAT(OTHERS, true)
VAUDIT_FEAT(SCHEDWAIT, true)

