obj-y += vivo_touchscreen_common.o
obj-y += vivo_touchscreen_config.o
obj-y += vivo_ts_function.o
obj-y += vivo_ts_ic_ctl.o
obj-y += vivo_ts_node.o
obj-y += vivo_touchscreen_virtual_key.o
obj-y += vivo_key.o
obj-y += vivo_ts_prox.o
