obj-$(CONFIG_BBK_FP_ID)		+= fp_id.o
obj-$(CONFIG_BBK_FP_HBM_INPUT)	+= fp_hbm_input.o
obj-$(CONFIG_BBK_GF9518)	+= gf9518/
obj-$(CONFIG_BBK_GSL7001)	+= gsl7001/
obj-$(CONFIG_BBK_FPC1511)	+= fpc1511/
obj-$(CONFIG_BBK_GF3208)	+= gf3208/

