ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/situation/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/sensorHub/inc_v1
ccflags-y += -I$(srctree)/drivers/misc/mediatek/scp/$(CONFIG_MTK_PLATFORM)
obj-$(CONFIG_MTK_SAR_HUB) += sar_factory.o
obj-$(CONFIG_MTK_SAR_SECONDARY_HUB) += sar_secondary_factory.o
obj-$(CONFIG_MTK_SAR_HUB)    +=  sarhub.o
obj-$(CONFIG_MTK_SAR_SECONDARY_HUB) += sarhub_secondary.o