
#include "himax_platform.h"
#include "himax_common.h"
#include "himax_ic_core.h"

/*#define HX_GAP_TEST*/
/*#define HX_INSPECT_LPWUG_TEST*/
/*#define HX_ACT_IDLE_TEST*/

char *g_rslt_data;

#define BS_RAWDATA	8
#define BS_NOISE	8
#define BS_OPENSHORT	0


#define	BS_LPWUG	1
#define	BS_LPWUG_dile	1



#define	BS_ACT_IDLE	1


/* skip notch & dummy */
#define SKIP_NOTCH_START	5
#define SKIP_NOTCH_END	10
/* TX+SKIP_NOTCH_START */
#define SKIP_DUMMY_START	23
/* TX+SKIP_NOTCH_END*/
#define SKIP_DUMMY_END	28


#define	NOISEFRAME	60
#define	UNIFMAX	500


/*Himax MP Password*/
#define	PWD_OPEN_START	0x77
#define	PWD_OPEN_END	0x88
#define	PWD_SHORT_START	0x11
#define	PWD_SHORT_END	0x33
#define	PWD_RAWDATA_START	0x00
#define	PWD_RAWDATA_END	0x99
#define	PWD_NOISE_START	0x00
#define	PWD_NOISE_END	0x99
#define	PWD_SORTING_START	0xAA
#define	PWD_SORTING_END	0xCC


#define PWD_ACT_IDLE_START		0x22
#define PWD_ACT_IDLE_END		0x44



#define PWD_LPWUG_START	0x55
#define PWD_LPWUG_END	0x66

#define PWD_LPWUG_IDLE_START	0x50
#define PWD_LPWUG_IDLE_END	0x60


/*Himax DataType*/
#define DATA_SORTING	0x0A
#define DATA_OPEN	0x0B
#define DATA_MICRO_OPEN	0x0C
#define DATA_SHORT	0x0A
#define DATA_RAWDATA	0x0A
#define DATA_NOISE	0x0F
#define DATA_BACK_NORMAL	0x00
#define DATA_LPWUG_RAWDATA	0x0C
#define DATA_LPWUG_NOISE	0x0F
#define DATA_ACT_IDLE_RAWDATA	0x0A
#define DATA_ACT_IDLE_NOISE	0x0F
#define DATA_LPWUG_IDLE_RAWDATA	0x0A
#define DATA_LPWUG_IDLE_NOISE	0x0F

/*Himax Data Ready Password*/
#define	Data_PWD0	0xA5
#define	Data_PWD1	0x5A

/* ASCII format */
#define ASCII_LF	(0x0A)
#define ASCII_CR	(0x0D)
#define ASCII_COMMA	(0x2C)
#define ASCII_ZERO	(0x30)
#define CHAR_EL	'\0'
#define CHAR_NL	'\n'
#define ACSII_SPACE	(0x20)
/* INSOECTION Setting */
int HX_CRITERIA_ITEM;
int HX_CRITERIA_SIZE;

typedef enum {
	HIMAX_INSPECTION_OPEN,
	HIMAX_INSPECTION_MICRO_OPEN,
	HIMAX_INSPECTION_SHORT,
	HIMAX_INSPECTION_RAWDATA,
	HIMAX_INSPECTION_WEIGHT_NOISE,
	HIMAX_INSPECTION_ABS_NOISE,
	HIMAX_INSPECTION_SORTING,
	HIMAX_INSPECTION_BACK_NORMAL,

	HIMAX_INSPECTION_GAPTEST_RAW,

	HIMAX_INSPECTION_ACT_IDLE_RAWDATA,
	HIMAX_INSPECTION_ACT_IDLE_NOISE,

	HIMAX_INSPECTION_LPWUG_RAWDATA,
	HIMAX_INSPECTION_LPWUG_NOISE,
	HIMAX_INSPECTION_LPWUG_IDLE_RAWDATA,
	HIMAX_INSPECTION_LPWUG_IDLE_NOISE,

} THP_INSPECTION_ENUM;

char *g_himax_inspection_mode[] = {
	"HIMAX_INSPECTION_OPEN",
	"HIMAX_INSPECTION_MICRO_OPEN",
	"HIMAX_INSPECTION_SHORT",
	"HIMAX_INSPECTION_RAWDATA",
	"HIMAX_INSPECTION_WEIGHT_NOISE",
	"HIMAX_INSPECTION_ABS_NOISE",
	//"HIMAX_INSPECTION_SORTING",
	//"HIMAX_INSPECTION_BACK_NORMAL",

	//"HIMAX_INSPECTION_GAPTEST_RAW",

	//"HIMAX_INSPECTION_ACT_IDLE_RAWDATA",
	//"HIMAX_INSPECTION_ACT_IDLE_NOISE",

	//"HIMAX_INSPECTION_LPWUG_RAWDATA",
	//"HIMAX_INSPECTION_LPWUG_NOISE",
	//"HIMAX_INSPECTION_LPWUG_IDLE_RAWDATA",
	//"HIMAX_INSPECTION_LPWUG_IDLE_NOISE",
	NULL

};

/* for criteria */
int **g_inspection_criteria;
int *g_inspt_crtra_flag;
char *g_hx_inspt_crtra_name[] = {
	"CRITERIA_RAW_MIN",
	"CRITERIA_RAW_MAX",
	"CRITERIA_SHORT_MIN",
	"CRITERIA_SHORT_MAX",
	"CRITERIA_OPEN_MIN",
	"CRITERIA_OPEN_MAX",
	"CRITERIA_MICRO_OPEN_MIN",
	"CRITERIA_MICRO_OPEN_MAX",
	"CRITERIA_NOISE_WT_MIN",
	"CRITERIA_NOISE_WT_MAX",
	"CRITERIA_NOISE_ABS_MIN",
	"CRITERIA_NOISE_ABS_MAX",
	//"CRITERIA_SORT_MIN",
	//"CRITERIA_SORT_MAX",

	//"CRITERIA_GAP_RAW_MIN",
	//"CRITERIA_GAP_RAW_MAX",

	//"ACT_IDLE_NOISE_MIN",
	//"ACT_IDLE_NOISE_MAX",
	//"ACT_IDLE_RAWDATA_MIN",
	//"ACT_IDLE_RAWDATA_MAX",

	//"LPWUG_NOISE_MIN",
	//"LPWUG_NOISE_MAX",
	//"LPWUG_RAWDATA_MIN",
	//"LPWUG_RAWDATA_MAX",
	//"LPWUG_IDLE_NOISE_MIN",
	//"LPWUG_IDLE_NOISE_MAX",
	//"LPWUG_IDLE_RAWDATA_MIN",
	//"LPWUG_IDLE_RAWDATA_MAX",
	NULL

};
typedef enum {
	IDX_RAWMIN		= 0,
	IDX_RAWMAX,
	IDX_SHORTMIN,
	IDX_SHORTMAX,
	IDX_OPENMIN,
	IDX_OPENMAX,
	IDX_M_OPENMIN,
	IDX_M_OPENMAX,
	IDX_WT_NOISEMIN,
	IDX_WT_NOISEMAX,
	IDX_ABS_NOISEMIN,
	IDX_ABS_NOISEMAX,
	IDX_SORTMIN,
	IDX_SORTMAX,

	IDX_GAP_RAWMAX,
	IDX_GAP_RAWMIN,

	IDX_ACT_IDLE_NOISE_MIN,
	IDX_ACT_IDLE_NOISE_MAX,
	IDX_ACT_IDLE_RAWDATA_MIN,
	IDX_ACT_IDLE_RAWDATA_MAX,

	IDX_LPWUG_NOISE_MIN,
	IDX_LPWUG_NOISE_MAX,
	IDX_LPWUG_RAWDATA_MIN,
	IDX_LPWUG_RAWDATA_MAX,

	IDX_LPWUG_IDLE_NOISE_MIN,
	IDX_LPWUG_IDLE_NOISE_MAX,
	IDX_LPWUG_IDLE_RAWDATA_MIN,
	IDX_LPWUG_IDLE_RAWDATA_MAX,

} HX_CRITERIA_ENUM;

/* Error code of Inspection */
typedef enum {
	HX_INSPECT_OK	= 0,               /* OK */
	HX_INSPECT_EFILE = 1,					/*Criteria file error*/
	HX_INSPECT_ERAW = 1 << 1,        /* Raw data error */
	HX_INSPECT_WT_ENOISE = 1 << 2,        /* Noise error */
	HX_INSPECT_ABS_ENOISE = 1 << 3,        /* Noise error */
	HX_INSPECT_EOPEN = 1 << 4,        /* Sensor open error */
	HX_INSPECT_EMOPEN = 1 << 5,        /* Sensor micro open error */
	HX_INSPECT_ESHORT = 1 << 6,        /* Sensor short error */

	HX_INSPECT_EGAP_RAW = 1 << 7,        /* Raw Data GAP  */

	HX_INSPECT_EACT_IDLE_RAW = 1 << 8,		   /* ACT_IDLE RAW ERROR */
	HX_INSPECT_EACT_IDLE_NOISE = 1 << 9,		   /* ACT_IDLE NOISE ERROR */

	HX_INSPECT_ELPWUG_RAW = 1 << 10,		   /* LPWUG RAW ERROR */
	HX_INSPECT_ELPWUG_NOISE = 1 << 11,		   /* LPWUG NOISE ERROR */
	HX_INSPECT_ELPWUG_IDLE_RAW = 1 << 12,		   /* LPWUG IDLE RAW ERROR */
	HX_INSPECT_ELPWUG_IDLE_NOISE = 1 << 13,		   /* LPWUG IDLE NOISE ERROR */

	HX_INSPECT_EGETRAW = 1 << 14,	/* Get raw data errors */
	HX_INSPECT_MEMALLCTFAIL = 1 << 15,	/* Get raw data errors */
	/*HX_INSPECT_ESPI = , */        /*SPI communication error,no use*/
} HX_INSPECT_ERR_ENUM;
