#
# Makefile for the focaltech touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-y	+=  focaltech_core.o
obj-y	+=  focaltech_ex_fun.o
obj-y	+=  focaltech_spi.o
obj-y	+=  focaltech_flash.o
obj-y	+=  focaltech_gesture.o
obj-y	+=  focaltech_esdcheck.o
obj-y	+=  focaltech_test.o
