#
# Makefile for the focaltech touchscreen drivers.
#

# Each configuration option enables a list of files.


obj-y += focaltech_upgrade_ft8006.o
obj-y += focaltech_upgrade_idc.o
obj-y += focaltech_upgrade_ft8736.o
obj-y += focaltech_upgrade_ft8719.o
obj-y += focaltech_flash_main.o
obj-y += focaltech_upgrade_test.o
