
obj-y += cts_i2c_driver.o
obj-y += cts_core.o
obj-y += cts_platform.o
obj-y += cts_sfctrlv2.o
obj-y += cts_spi_flash.o
obj-y += cts_firmware.o
obj-y += cts_tool.o
obj-y += cts_sysfs.o
obj-y += cts_test.o
obj-y += cts_charger_detect.o
obj-y += cts_earjack_detect.o
obj-y += cts_strerror.o
obj-y += cts_vendor_vivo.o