#ifeq ($(CONFIG_SAMSUNG_PRODUCT_SHIP), y)
#  obj-$(CONFIG_TOUCHSCREEN_SEC_TS)   += sec_ts.o sec_ts_fw.o sec_ts_fn.o sec_ts_only_vendor.o
#else
#  obj-$(CONFIG_TOUCHSCREEN_SEC_TS)   += sec_ts.o sec_ts_fw.o sec_ts_fn.o sec_ts_only_vendor.o
#endif
obj-y += sec_ts.o
obj-y += sec_ts_fw.o
obj-y += sec_ts_fn.o
obj-y += sec_ts_only_vendor.o
#obj-y += sec_ts_custom_fn.c
